import React from 'react';

export default function LandingPage({ onStart }) {
  const features = [
    {
      title: 'AI-Driven Insights',
      description:
        'Each answer is accompanied by context-aware explanations generated by our proprietary large-language-model pipeline.',
      icon: (
        <svg
          xmlns="http://www.w3.org/2000/svg"
          fill="none"
          viewBox="0 0 24 24"
          strokeWidth={1.5}
          stroke="currentColor"
          className="w-8 h-8 text-emerald-400"
        >
          <path
            strokeLinecap="round"
            strokeLinejoin="round"
            d="M12 4.5v15m7.5-7.5h-15"
          />
        </svg>
      ),
    },
    {
      title: 'Adaptive Difficulty',
      description:
        'The question set continuously adapts to your performance, ensuring an optimal learning curve every session.',
      icon: (
        <svg
          xmlns="http://www.w3.org/2000/svg"
          fill="none"
          viewBox="0 0 24 24"
          strokeWidth={1.5}
          stroke="currentColor"
          className="w-8 h-8 text-emerald-400"
        >
          <path
            strokeLinecap="round"
            strokeLinejoin="round"
            d="M3.75 12h16.5" />
          <path
            strokeLinecap="round"
            strokeLinejoin="round"
            d="M12 3.75v16.5" />
        </svg>
      ),
    },
    {
      title: 'Real-Time Analytics',
      description:
        'Beautiful dashboards track your mastery in real time, highlighting strengths and surfacing blind spots before exams.',
      icon: (
        <svg
          xmlns="http://www.w3.org/2000/svg"
          fill="none"
          viewBox="0 0 24 24"
          strokeWidth={1.5}
          stroke="currentColor"
          className="w-8 h-8 text-emerald-400"
        >
          <path
            strokeLinecap="round"
            strokeLinejoin="round"
            d="M3 3v18h18" />
          <path
            strokeLinecap="round"
            strokeLinejoin="round"
            d="M7 15v3m4-8v8m4-12v12" />
        </svg>
      ),
    },
  ];

  return (
    <div className="relative w-full overflow-hidden bg-slate-950 text-white">
      {/*  Decorative blurred blobs  */}
      <div className="pointer-events-none absolute inset-0 -z-10 overflow-hidden">
        <div className="absolute -top-32 left-1/2 h-96 w-96 -translate-x-1/2 rounded-full bg-emerald-500/20 blur-3xl" />
        <div className="absolute bottom-0 right-0 h-96 w-96 translate-x-1/3 translate-y-1/3 rounded-full bg-lime-500/20 blur-3xl" />
      </div>

      {/*  Navigation placeholder  */}
      <header className="mx-auto flex max-w-7xl items-center justify-between px-6 py-6">
        <span className="text-2xl font-extrabold tracking-tight text-transparent bg-gradient-to-r from-emerald-400 via-lime-400 to-green-600 bg-clip-text drop-shadow-lg">
          EvaLime
        </span>
        <button className="btn btn-outline btn-sm" onClick={onStart}>
          Sign&nbsp;in
        </button>
      </header>

      {/*  Hero Section  */}
      <section className="mx-auto flex max-w-7xl flex-col items-center px-6 py-24 text-center md:py-40">
        <h1 className="text-4xl font-extrabold leading-tight sm:text-6xl md:text-7xl">
          Learn&nbsp;
          <span className="text-transparent bg-gradient-to-r from-emerald-400 via-lime-400 to-green-600 bg-clip-text">
            faster
          </span>
          , retain&nbsp;
          <span className="text-transparent bg-gradient-to-r from-emerald-400 via-lime-400 to-green-600 bg-clip-text">
            longer
          </span>
        </h1>
        <p className="mt-6 max-w-3xl text-lg text-slate-300 md:text-xl">
          EvaLime transforms traditional multiple-choice practice into an intelligent, data-driven learning experience designed for the&nbsp;AI era.
        </p>
        <div className="mt-10 flex flex-wrap items-center justify-center gap-4">
          <button className="btn btn-primary px-8 text-base" onClick={onStart}>
            Get&nbsp;Started
          </button>
          <a
            href="#features"
            className="btn btn-ghost px-8 text-base text-slate-300 hover:text-white"
          >
            Learn&nbsp;More
          </a>
        </div>
      </section>

      {/*  Features Section  */}
      <section
        id="features"
        className="mx-auto max-w-7xl space-y-16 px-6 py-24 sm:py-32"
      >
        <h2 className="text-center text-4xl font-bold tracking-tight sm:text-5xl">
          Built for ambitious learners
        </h2>
        <div className="grid gap-8 md:grid-cols-3">
          {features.map(feature => (
            <div
              key={feature.title}
              className="group relative overflow-hidden rounded-xl border border-white/10 bg-slate-900/50 p-8 backdrop-blur transition hover:-translate-y-1 hover:border-emerald-500 hover:shadow-emerald-500/10"
            >
              <div className="mb-4 flex h-12 w-12 items-center justify-center rounded-lg bg-slate-800 group-hover:bg-emerald-600">
                {feature.icon}
              </div>
              <h3 className="text-xl font-semibold mb-2">
                {feature.title}
              </h3>
              <p className="text-sm text-slate-400">
                {feature.description}
              </p>
            </div>
          ))}
        </div>
      </section>

      {/*  Call To Action  */}
      <section className="relative isolate overflow-hidden py-24 sm:py-32">
        <div className="absolute inset-0 -z-10 bg-gradient-to-b from-emerald-600/40 via-emerald-700/30 to-transparent blur-xl" />
        <div className="mx-auto max-w-4xl px-6 text-center">
          <h2 className="text-3xl font-bold tracking-tight text-white sm:text-4xl">
            Ready to see your scores soar?
          </h2>
          <p className="mt-4 text-lg leading-8 text-slate-300">
            Join thousands of learners leveraging EvaLime to ace their next exam.
          </p>
          <button
            className="btn btn-accent mt-10 px-10 text-base"
            onClick={onStart}
          >
            Start Practicing
          </button>
        </div>
      </section>

      {/*  Footer  */}
      <footer className="border-t border-white/10 px-6 py-10 text-center text-sm text-slate-500">
        © {new Date().getFullYear()} EvaLime. Crafted with&nbsp;
        <span role="img" aria-label="love">
          ❤️
        </span>{' '}
        & TailwindCSS.
      </footer>
    </div>
  );
}
